### ISSUE TITLE
Signing a message for authentication

### ISSUE THREAD

**Issue by tuncatunc** [kaddex-org/x-wallet#39]
I need to sign a message and verify that the message is signed by the public key for authentication.
I'm following  `https://docs.kaddex.com/kaddex-features/getting-started/x-wallet/x-wallet-api#sign-command`
```javascript
    kadena.request({
      method: "kda_requestSign",
      data: {
        networkId: `testnet04`,
        signingCmd: `(free.AAAAA.details "ROOT")`,
      },
    }).then((response) => {
      console.log("Signing request", response);
    }).catch((error) => {
      console.log("Signing request error", error);
    });
```
and nothing happens.

I also followed the source code and couldn't figure out how signing work?

Thank you

**Comment by murataka** [comment]
Bumping with a fail message 

```
{
    "status": "fail",
    "message": "Fail to get signedCmd"
}
```
![image](https://user-images.githubusercontent.com/5358438/208726830-d38d1b77-c146-416c-8ee0-0229cbf6e383.png)

**Comment by ants88** [comment]
Your command should have the right pact form, like this
`{
  pactCode:
    '(free.AAAAA.details "ROOT"',
  caps: [
    {
      role: 'transfer capability',
      description: 'transfer token',
      cap: {
        name: 'coin.TRANSFER',
        args: ['k:abcdefghijklmnopqrstuvwxyz', 'aaaaaaaaaaaaa', 123],
      },
    },
  ],
  sender: 'kaddex-free-gas',
  gasLimit: 10000,
  gasPrice: 1e-7,
  chainId: '2',
  ttl: 600,
  envData: {
    'user-ks': { pred: 'keys-all', keys: ['abcdefghijklmnopqrstuvwxyz'] },
    a: 1,
  },
  signingPubKey: 'abcdefghijklmnopqrstuvwxyz',
  networkId: 'mainnet01',
  networkVersion: '0.0',
}`

then the right xwallet signing api payload should be something like this
``` 
window.kadena.request({
      method: 'kda_requestSign',
    data:{
        networkId: 'mainnet01',
        signingCmd: {
  pactCode:
    '(free.AAAAA.details "ROOT")',
  caps: [
    {
      role: 'transfer capability',
      description: 'transfer token',
      cap: {
        name: 'coin.TRANSFER',
        args: ['k:abcdefghijklmnopqrstuvwxyz', 'aaaaaaaaaaaaa', 123],
      },
    },
  ],
  sender: 'abc',
  gasLimit: 10000,
  gasPrice: 1e-7,
  chainId: '2',
  ttl: 600,
  envData: {
    'user-ks': { pred: 'keys-all', keys: ['abcdefghijklmnopqrstuvwxyz'] },
    a: 1,
  },
  signingPubKey: 'abcdefghijklmnopqrstuvwxyz',
  networkId: 'mainnet01',
  networkVersion: '0.0',
}
    },
    }).then(res => console.log(res)).catch(err => console.log(err))

**Comment by tuncatunc** [comment]
I'm able to sign a message with following, now I'm trying to verify the signed message.
Please find the working app here
https://sign-message-with-x-wallet-omolgjikq-tunca.vercel.app/

```js
async function sign() {
  const xWalletAccount = await kadena.request({
    method: "kda_requestAccount",
    networkId: NETWORKID,
  });

  console.log("xWalletAccount", xWalletAccount);
  // get message from message input
  const message = document.getElementById("message").value;

  const signingCmd = {
    networkId: NETWORKID,
    sender: xWalletAccount.wallet.account,
    chainId: 1,
    gasPrice: 0.0000001,
    gasLimit: 60000,
    ttl: 28000,
    pactCode: message,
    envData: {},
  };

  const signedCmd = await kadena.request({
    method: "kda_requestSign",
    data: {
      networkId: NETWORKID,
      signingCmd,
    },
  });

  console.log("signedCmd", signedCmd);
  // set signature to signature input
  document.getElementById("signature").value = signedCmd.signedCmd.sigs[0].sig;
  return signedCmd;
}
```
