### ISSUE TITLE
kda_sendKadena doesn't return the txid 

### ISSUE THREAD

**Issue by tuncatunc** [kaddex-org/x-wallet#42]
`kda_sendKadena` doesn't return the transaction id if the request is submitted to the blockchain successfully.
It's important for the API users to have that TXid.
Can you please add that too?

https://docs.kaddex.com/kaddex/getting-started/x-wallet/x-wallet-api#send-tokens-to-another-account

**Comment by ants88** [comment]
you can listen to the event `res_sendKadena`. You will get the requestKey. The doc will be updated with this info. Thank you

**Comment by tuncatunc** [comment]
This shows an popup window and confirms send kda, however `res_sendKadena` event is never called.

```javascript
    const data = window.kadena.request({
      method: 'kda_sendKadena',
      data: {
        networkId: 'testnet04',
        account: 'tunca',
        sourceChainId: '1',
        chainId: '1',
        amount: depositAmount,
      },
    })
```
```javascript
  useEffect(() => {
    window.kadena.on('res_sendKadena', (data) => {
      console.log(data) //<== is never called
    })
  }, [])
```
