### ISSUE TITLE
`kda_requestQuickSign` always returns `error: 'QuickSign fail: wallet public key not found'`.

### ISSUE THREAD

**Issue by mubashir-f** [kaddex-org/x-wallet#47]
I was using `kda_requestQuickSign` to sign continuation command, and it was working completely fine before last update to ecko-wallet, after 2.4.2 `kda_requestQuickSign` always returns `error: 'QuickSign fail: wallet public key not found'`

**Here is my Request**
```
const signedCmd = await window.kadena.request({
    method: "kda_requestQuickSign",
    data: {
        networkId: process.env.networkId,
        commandSigDatas: [
            {
                sigs: [
                    {
                        pubKey: "368852bf231ce4f362bb770ea9c5d7e22671306ebfcdfd58d9a6bf4f393a6069",
                    },
                ],
                cmd: contCmd.cmd,
            },
        ],
    },
});
```

**What i have tried so far to replicate error**

1. Tried reinstalling ecko-wallet.
2. Cleared browser cache.
3. Tried different kadena accounts.
4. double check public key at request and at active ecko-wallet

**Active wallet**
![Screenshot (4)](https://user-images.githubusercontent.com/74946436/230850176-cd6fa864-c0bc-41e5-82a6-1388a807ccf4.png)

**Error**
```
error : "QuickSign fail: wallet public key not found"
status : "fail"
```

**Comment by trendzetter** [comment]
I think there were changes to the walletconnect and signing specifications and some things were renamed too:
https://github.com/kadena-io/KIPs/commit/0de3bbdd6a6f54a6cda27d9c0ef5a12fc4e26453
https://github.com/kadena-io/KIPs/commits/02c82f398d40cf1b58d15ab13483e1b310d7e437/kip-0015.md

**Comment by ants88** [comment]
Thanks for your report, this bug will be fixed with https://github.com/eckoDAO-org/ecko-wallet/pull/49
