### ISSUE TITLE
Imported keys give invalid signatures

### ISSUE THREAD

**Issue by CryptoPascal31** [kaddex-org/x-wallet#64]
I import a key in EckoWallet:

For my example:
```yaml
public: d32071a167de2a376ab9b1de582db52fe502f39b71df8d3bede8a71802ffed9f
secret: f72a8ec5950804f354aebe24c84b965fb8f23be2abd18e2ec5f3ce2a1339af3d
```
Account: ```k:d32071a167de2a376ab9b1de582db52fe502f39b71df8d3bede8a71802ffed9f```

You can use this key for reproducing the issue. I created it specifically for this case. It has some funds on Testnet. Feel free to play with it.

I'm able to transfer KDAs with eckoWallet and this account:
Proof: https://explorer.chainweb.com/testnet/txdetail/ymEVe5gnSc3A9eiqIh3up2w7uduaPH9DFKrMrWw238w

**But it seems that the function "Sign Hash Transaction" gives an INVALID signature**:
![Screenshot from 2024-01-25 13-23-44](https://github.com/eckoDAO-org/ecko-wallet/assets/95504829/ff8aea6a-c6ba-4ab2-9a9c-057cff16746f)

![Screenshot from 2024-01-25 13-25-55](https://github.com/eckoDAO-org/ecko-wallet/assets/95504829/a5f9d3f2-8943-443a-9f10-df2d02e2d5bb)

We can confirm that the signature is invalid with this very handy tool: https://cyphr.me/ed25519_tool/ed.html (don't forget to use base64 as msg encoding).

**Note**: this works well with a "passphrase generated" key from the same wallet:
![Screenshot from 2024-01-25 13-26-42](https://github.com/eckoDAO-org/ecko-wallet/assets/95504829/47b62c0f-2a89-4304-8c2d-77db4a65ddf6)

**Note-2** : Using the "imported key" via Quicksign API have the same issue (in fact, this is how I discovered it)

**Comment by ants88** [comment]
We are on it, thanks

**Comment by ants88** [comment]
Fixed in this commit https://github.com/eckoDAO-org/ecko-wallet/commit/45ee5a52cfbc1f938242fdc6a9e9e92b6f339911.
We will publish the new version asap

**Comment by CryptoPascal31** [comment]
I've tested the new version in both cases:
   - Sign Hash UI
   - Quicksign

It works perfectly, good work => I close the issue
