### ISSUE TITLE
When I try to install I get error. 

### ISSUE THREAD

**Issue by mainul-islam-faruqi** [kaddex-org/x-wallet#8]
`npm install` failed
<img width="760" alt="image" src="https://user-images.githubusercontent.com/53335400/162983334-95612fd0-df2e-4bd0-ade1-aa565d6baaa5.png">

**Comment by ants88** [comment]
Please provide your npm and node version

**Comment by mainul-islam-faruqi** [comment]
<img width="235" alt="image" src="https://user-images.githubusercontent.com/53335400/162986812-f93f628c-8c21-4444-b0b8-9b77068f593d.png">

**Comment by mainul-islam-faruqi** [comment]
I also tried. 
delete node_modules & package-lock.json 
`npm cache clean -f `
then `npm install`
this was also failed.

**Comment by ants88** [comment]
Have you installed emscripten first? as written in the readme?

**Comment by mainul-islam-faruqi** [comment]
yes. I have already emscripten. when I ran `emsdk help`. it works properly. 
<img width="516" alt="image" src="https://user-images.githubusercontent.com/53335400/162999025-5ab1bfc5-9e27-4f62-ad97-16f56737f1a6.png">
If it wouldn't install, I would say emsdk doesn't recognize something like this.

**Comment by CrazyPythonLover1** [comment]
`source ./emsdk_env.sh`
What does mean by this command? I ran this on my windows machine but failed. 
Here is the error. 
<img width="820" alt="image" src="https://user-images.githubusercontent.com/53335400/163018602-52e4c20c-486f-41c8-80f0-00b93849732f.png">
emsdk install and activate ran properly.

**Comment by mainul-islam-faruqi** [comment]
I tried to install emscripten as written in a readme file(step by step). emscripten is installed and Activated PATH and other environment variables in the current terminal.
when trying to install the x-wallet. Got the same error. 
<img width="757" alt="image" src="https://user-images.githubusercontent.com/53335400/163106935-30b232c6-1879-4413-bd1c-40365fd6c0c4.png">
this error is for not to get the git in the current terminal.

**Comment by mainul-islam-faruqi** [comment]
`npm install` didn't work because of the node-sass version. we need to use supported node version for node-sass. 

https://www.npmjs.com/package/node-sass
